### ISSUE TITLE
imgproxy-rails

### ISSUE THREAD

**Issue by yaroslav** [imgproxy/imgproxy-rails#1]
# imgproxy-rails

## Context

[imgproxy.rb](https://github.com/imgproxy/imgproxy.rb) is a framework-agnostic Ruby Gem for [imgproxy](https://imgproxy.net) that includes proper support for Ruby on Rails' most popular image attachment options: Active Storage and Shrine.

The problem is—user must use imageproxy specific API:

```ruby
user.avatar.imgproxy_url(width: 250, height: 250)
```

But wouldn't that be awesome to be able to use imageproxy as an adapter to Active Storage? For example, to use vips/ImageMagick in dev and imageproxy in prod.

And we absolutely can do just that, thanks to [ActiveStorage::Variant API](https://api.rubyonrails.org/v5.2.0/classes/ActiveStorage/Variant.html) and [Proxy mode](https://edgeguides.rubyonrails.org/active_storage_overview.html#proxy-mode).

Given the following configuration:

```ruby
# development.rb
config.active_storage.resolve_model_to_route = :rails_storage_proxy

# production.rb
config.active_storage.resolve_model_to_route = :imgproxy_active_storage
```

The following HTML snippet will generate different URLs in dev and prod:

```erb
# show.erb.html
<%= image_tag Current.user.avatar.variant(resize: "100x100") %>
```

In dev, it will generate a URL like this:

```html
<img src="http://localhost:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWHc9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c35e9a616c29da2dfa10a385bae7172526e7961/me.png">
```

In prod, it will generate a URL like this:

```html
<img src="https://imgproxy.example.com/8uVB2dYrZVOdG-1tekFjNJZ7s7VHDViXJbu9TcQavQ8/fn:me.png/aHR0cDovL2xvY2Fs/aG9zdDozMDAwL3Jh/aWxzL2FjdGl2ZV9z/dG9yYWdlL2Jsb2Jz/L3Byb3h5L2V5SmZj/bUZwYkhNaU9uc2li/V1Z6YzJGblpTSTZJ/a0pCYUhCQldIYzlJ/aXdpWlhod0lqcHVk/V3hzTENKd2RYSWlP/aUppYkc5aVgybGtJ/bjE5LS0wYzM1ZTlh/NjE2YzI5ZGEyZGZh/MTBhMzg1YmFlNzE3/MjUyNmU3OTYxL21l/LnBuZw">
```

## Proposal

Create a gem, that will make it possible to turn on imageproxy mode via `resolve_model_to_route` (here is [an example from rails codebase](https://github.com/rails/rails/blob/3258979977e8aa80c9592ad105ae8b76ea77064c/activestorage/config/routes.rb#L33)):
Parse `ActiveStorage::Variant` transformation attributes and generate imageproxy URL for variants (representations), but use default Rails proxying for original files.

Note that [image_processing](https://github.com/janko/image_processing) supports only a subset of all imageproxy options.

Let's think if we want to allow users to specify imgproxy-specific [parameters](https://github.com/imgproxy/imgproxy.rb/blob/master/lib/imgproxy/options.rb), and if yes, how to do that.

## Tasks

- [ ] Propose an API for imgproxy specific options support (right in this issue)
- [ ] Wait for approval/suggestions
- [ ] Implement the proposed functionality
- [ ] Don't forget about tests 😉
